name: Deploy portfolio to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy using PowerShell and SCP
      - name: Deploy to server using SCP
        run: |
          # Variabelen instellen
          $ServerHost = "${{ vars.SERVER_HOST }}"
          $ServerUser = "${{ vars.SERVER_USER }}"
          $ServerPath = "${{ vars.SERVER_PATH }}"
          $PrivateKey = "${{ secrets.DEPLOY_KEY }}"  # Inhoud van de private key
          
          # Tijdelijke locatie voor de private key
          $TempKeyPath = "$env:TEMP\deploy_key.pem"
          
          # Private key opslaan in een bestand
          Set-Content -Path $TempKeyPath -Value $PrivateKey -NoNewline
          
          # Toegangsrechten aanpassen (beveiliging)
          & icacls $TempKeyPath /inheritance:r /grant:r "SYSTEM:F"
      
          # SCP uitvoeren om bestanden te kopiëren
          $SourcePath = "${{ github.workspace }}\*"
          $RemotePath = "${ServerUser}@${ServerHost}:${ServerPath}"
          scp -i $TempKeyPath -r $SourcePath $RemotePath
      
          # Opruimen van het tijdelijke bestand
          Remove-Item -Path $TempKeyPath
        shell: powershell
