name: Deploy portfolio to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy using PowerShell and SCP
      - name: Deploy to server using SCP
        run: |
          # Define variables
          $ServerHost = "${{ vars.SERVER_HOST }}"
          $ServerUser = "${{ vars.SERVER_USER }}"
          $ServerPath = "${{ vars.SERVER_PATH }}"
          
          # Use SCP to transfer files
          $KeyPath = "C:\keys\vpn_server_key.pem"
          $SourcePath = "${{ github.workspace }}\*"
          $RemotePath = "${ServerUser}@${ServerHost}:${ServerPath}"
          
          # Use SCP with the stored private key
          scp -i $KeyPath -r $SourcePath $RemotePath
        shell: powershell
