name: Deploy portfolio to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy using PowerShell and SCP
      - name: Deploy to server using SCP
        run: |
          # Define variables
          $ServerHost = "${{ vars.SERVER_HOST }}"
          $ServerUser = "${{ vars.SERVER_USER }}"
          $ServerPath = "${{ vars.SERVER_PATH }}"
          $PrivateKey = "${{ secrets.DEPLOY_KEY }}"
          
          # Create temporary private key file
          $TempKeyPath = "$env:TEMP\deploy_key.pem"
          Set-Content -Path $TempKeyPath -Value $PrivateKey -NoNewline
          & icacls $TempKeyPath /inheritance:r /grant:r "SYSTEM:F"

          # Use SCP to transfer files
          $SourcePath = "${{ github.workspace }}\*"
          $RemotePath = "$ServerUser@$ServerHost:$ServerPath"
          scp -i $TempKeyPath -r $SourcePath $RemotePath

          # Clean up private key
          Remove-Item -Path $TempKeyPath
        shell: powershell
